-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Remotes.UnreliableRemoteEvent

while true do
    firesignal(Event.OnClientEvent, 
        "ThirstChanged",
        100
    )
    wait(1) -- Пауза в 1 секунду между вызовами
end